{% set version = "2.7.3" %}
{% set build = 2 %}
{% set build_string = '' %}

{% set build_string = 'mkl_' %}              # [(linux64 or win) and mkl_support == 'mkl']
{% set build = build + 100 %}                # [(linux64 or win) and mkl_support == 'mkl']

package:
  name: numexpr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/numexpr/numexpr-{{ version }}.tar.gz
  sha256: 43616529f9b7d1afc83386f943dc66c4da5e052f00217ba7e3ad8dd1b5f3a825

build:
  string: "{{ build_string }}py{{ py }}h{{ PKG_HASH }}_{{ build }}"
  number: {{ build }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - mkl                                    # [(linux64 or win) and mkl_support == 'mkl']
    - mkl-devel                              # [(linux64 or win) and mkl_support == 'mkl']
    - numpy
    - pip
    - python
    - setuptools
  run:
    - libblas * *mkl                         # [(linux64 or win) and mkl_support == 'mkl']
    - mkl                                    # [(linux64 or win) and mkl_support == 'mkl']
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - numexpr
    - numexpr.interpreter

about:
  home: https://github.com/pydata/numexpr
  license: MIT
  license_file: LICENSE.txt
  summary: Fast numerical expression evaluator for NumPy.
  description: |
    Numexpr is a fast numerical expression evaluator for NumPy. With it,
    expressions that operate on arrays (like "3*a+4*b") are accelerated and use
    less memory than doing the same calculation in Python.
  doc_url: https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide
  dev_url: https://github.com/pydata/numexpr

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - scopatz
    - djkirkham
